name: Build and publish

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:

  build:

    runs-on: ubuntu-latest
    name: Run tests

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.20.13'

      # - name: Ensure linux agent compiles
      #   run: |
      #     ARCHS='amd64 386 arm64 arm'
      #     for i in ${ARCHS}; do
      #       env CGO_ENABLED=0 GOOS=linux GOARCH=${i} go build -ldflags "-s -w" && mv rmmagent rmmagent-linux-${i}
      #     done
      
      # - name: Ensure windows agent compiles
      #   run: |
      #     ARCHS='amd64 386'
      #     for i in ${ARCHS}; do
      #       env CGO_ENABLED=0 GOOS=windows GOARCH=${i} go build -ldflags "-s -w" && mv rmmagent rmmagent-windows-${i}
      #     done
      
      - name: Ensure mac agent compiles
        run: |
          ARCHS='arm64'
          for i in ${ARCHS}; do
            env CGO_ENABLED=0 GOOS=darwin GOARCH=${i} go build -ldflags "-s -w" && mv rmmagent rmmagent-macos-${i}
          done

      - name: Clear old relase with same tag
        uses: liudonghua123/delete-release-action@v1
        with:
          release_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
  
      - name: Create new release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload release
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["rmmagent/rmmagent-*"]'